#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> RWOut;
float 	Seed;

// reference: https://www.shadertoy.com/view/ltB3zD 
#define PHI 1.61803398874989484820459 
inline float GoldNoise(float2 xy, float seed)
{
	return frac(tan(distance(xy*PHI, xy)*seed)*xy.x);
}

// create gold noise 
[numthreads(8,8,1)]
void Main (uint3 id : SV_DispatchThreadID)
{
	RWOut[id.xy] = float4(
		GoldNoise(id.xy + 1, frac(Seed)+1.0),
        GoldNoise(id.xy + 1, frac(Seed)+2.0),
        GoldNoise(id.xy + 1, frac(Seed)+3.0),
        GoldNoise(id.xy + 1, frac(Seed)+4.0));
}