#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> RWOut;
float 	Seed;

// static noise function  
#define PHI 1.61803398874989484820459
float GoldNoise(float2 xy, float seed)
{
	return frac(tan(distance(xy*PHI, xy)*seed)*xy.x);
}

// create static noise 
[numthreads(8,8,1)]
void Main (uint3 id : SV_DispatchThreadID)
{
	RWOut[id.xy] = float4(
        GoldNoise(id.xy + 1, Seed + 1.0f), 
        GoldNoise(id.xy + 1, Seed + 2.0f),
        GoldNoise(id.xy + 1, Seed + 3.0f),
        1);
}