#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> RWOut;
Texture2D<float4> RGrid;

int2   TexSize;
int    GridSize;

[numthreads(32,32,1)]
void Main(
    uint3 Id : SV_DispatchThreadID
)
{
	float Distance = GridSize * 3;
	int2 MaxGrid = TexSize / GridSize;
	int2 CenterGrid = Id.xy / GridSize;
	
	for(int i = -1; i <= 1; ++i)
	{
		for (int j = -1; j <= 1; ++j)
		{
			int2 RawGrid = CenterGrid + int2(j, i);
			int2 Grid = (RawGrid + MaxGrid) % MaxGrid;
			float2 GridCenter = (RawGrid + RGrid[Grid].xy - 0.5f) * GridSize;
			Distance = min(distance(Id.xy, GridCenter),Distance);
		}
	}

	RWOut[Id.xy] = Distance / GridSize;
}